# TCL File Generated by Component Editor 13.1
# Wed Nov 06 11:40:30 CET 2013
# DO NOT MODIFY


#
# avalon_pwm "Avalon PWM" v2013.11.6
# G. JOLI 2013.11.06.11:40:30
# 32bits RTL PWM
# Version 2017.02.15: widen the address bus to 10 bits to have 4096 bytes
#                     of addressing (better Linux compatibility)
#

#
# request TCL package from ACDS 13.1
#
package require -exact qsys 13.1


#
# module avalon_pwm
#
set_module_property DESCRIPTION "32bits RTL PWM "
set_module_property NAME avalon_pwm
set_module_property VERSION 2017.02.15
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP ALSE
set_module_property AUTHOR "G. JOLI - gjoli@alse-fr.com"
set_module_property DISPLAY_NAME "Avalon PWM"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# DTS Info
set_module_assignment embeddedsw.dts.vendor "ALSE"
set_module_assignment embeddedsw.dts.name "avalon_pwm"
set_module_assignment embeddedsw.dts.group "avalon_pwm"

set_module_assignment embeddedsw.dts.compatible {ALSE,avalon_pwm}

#
# file sets
#
add_fileset quartus_synth QUARTUS_SYNTH "" "Quartus Synthesis"
set_fileset_property quartus_synth TOP_LEVEL avalon_pwm
set_fileset_property quartus_synth ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file avalon_pwm.v VERILOG PATH avalon_pwm.v TOP_LEVEL_FILE

add_fileset sim_verilog SIM_VERILOG "" "Verilog Simulation"
set_fileset_property sim_verilog TOP_LEVEL avalon_pwm
set_fileset_property sim_verilog ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file avalon_pwm.v VERILOG PATH avalon_pwm.v

add_fileset sim_vhdl SIM_VHDL "" "VHDL Simulation"
set_fileset_property sim_vhdl TOP_LEVEL avalon_pwm
set_fileset_property sim_vhdl ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file avalon_pwm.vhd VHDL PATH avalon_pwm.vhd


#
# parameters
#
add_parameter duty_default INTEGER 0 ""
set_parameter_property duty_default DEFAULT_VALUE 0
set_parameter_property duty_default DISPLAY_NAME duty_default
set_parameter_property duty_default TYPE INTEGER
set_parameter_property duty_default UNITS None
set_parameter_property duty_default ALLOWED_RANGES -2147483648:2147483647
set_parameter_property duty_default DESCRIPTION ""
set_parameter_property duty_default HDL_PARAMETER true
set_parameter_property duty_default VISIBLE true
add_parameter modulus_default INTEGER 255 ""
set_parameter_property modulus_default DEFAULT_VALUE 255
set_parameter_property modulus_default DISPLAY_NAME modulus_default
set_parameter_property modulus_default TYPE INTEGER
set_parameter_property modulus_default UNITS None
set_parameter_property modulus_default ALLOWED_RANGES -2147483648:2147483647
set_parameter_property modulus_default DESCRIPTION ""
set_parameter_property modulus_default HDL_PARAMETER true
add_parameter debug INTEGER 0
set_parameter_property debug DEFAULT_VALUE 0
set_parameter_property debug DISPLAY_NAME debug
set_parameter_property debug TYPE INTEGER
set_parameter_property debug ENABLED false
set_parameter_property debug UNITS None
set_parameter_property debug HDL_PARAMETER true


#
# display items
#


#
# connection point clock
#
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


#
# connection point reset
#
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


#
# connection point avalon_slave
#
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clock
set_interface_property avalon_slave associatedReset reset
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitStates 0
set_interface_property avalon_slave readWaitTime 0
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave address address Input 10
add_interface_port avalon_slave write write Input 1
add_interface_port avalon_slave writedata writedata Input 32
add_interface_port avalon_slave read read Input 1
add_interface_port avalon_slave readdata readdata Output 32
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0

#
# connection point conduit
#
add_interface conduit conduit end
set_interface_property conduit associatedClock clock
set_interface_property conduit associatedReset reset
set_interface_property conduit ENABLED true
set_interface_property conduit EXPORT_OF ""
set_interface_property conduit PORT_NAME_MAP ""
set_interface_property conduit CMSIS_SVD_VARIABLES ""
set_interface_property conduit SVD_ADDRESS_GROUP ""

add_interface_port conduit pwm_out export Output 1



